# Generated by Django 3.0.4 on 2020-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpool',
            name='weighting',
            field=models.IntegerField(default=0, verbose_name='排列权重'),
            preserve_default=False,
        ),
    ]
