# Generated by Django 3.0.4 on 2020-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_questionpool_weighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpool',
            name='weighting',
            field=models.IntegerField(blank=True, null=True, verbose_name='排列权重'),
        ),
    ]
