# Generated by Django 3.0.4 on 2020-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200401_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinkBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.CharField(max_length=300, verbose_name='链接')),
                ('note', models.TextField(default='备注信息', verbose_name='备注信息')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmark',
            },
        ),
    ]
